language: node_js
node_js:
  - 7
before_install:
  - npm update -g npm
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
script:
  - npm run webpack
  - ./node_modules/.bin/karma start --browsers Chrome --single-run
after_success:
  - npm run codecov

sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
